### ISSUE TITLE
Allow multiple organisms in a single load

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/vcf_genotypes#2]
Currently only genotypes for a single organism can be loaded from a single file, but we may have diversity panels with mixed species. One way to accomplish this would be to optionally allow the organism to be specified on a per-sample basis in the user-supplied samples list.

**Comment by carolyncaron** [comment]
A second option is to check the database for a stock or germplasm without assuming organism. If the stock/germplasm is not unique, prompt the user through drush to choose the one they intended. This could get tedious for hundreds of samples but we could also bypass multiple prompts by allowing an additional column in the samples file specifying the common name of the organism.

When a user interface is being implemented, we can avoid the samples file entirely and use autocompletes for the user to select stocks/germplasm, which thankfully will also take care of this problem.

**Comment by carolyncaron** [comment]
The option to supply multiple organisms has now been implemented. This can be done providing it for each sample within the samples file in the 7th column (6th column is delegated for germplasm type (Individual, Variety, etc..) and is also a new feature). 

This issue will remain open until:
- [x]  Docs are fully updated to reflect this feature
- [x]  We appropriately handle locations of variants on the genome of a particular organism, which may differ from some organisms of our samples (ie. the closest reference genome available is of a related species)

**Comment by carolyncaron** [comment]
Oops... didn't mean to close the issue immediately after commenting that it would remain open!

**Comment by laceysanderson** [comment]
Fixed by PR 🎉
