### ISSUE TITLE
Error reported with psql 10+

### ISSUE THREAD

**Issue by bradfordcondon** [UofS-Pulse-Binfo/vcf_genotypes#27]
Same problem as reported in https://github.com/UofS-Pulse-Binfo/nd_genotypes/issues/26 the installer uses regexp to check the postgres version but assumes 9.x

**Comment by laceysanderson** [comment]
This should be fixed now @bradfordcondon, thanks for letting us know!

**Comment by bradfordcondon** [comment]
```
genotypes_loader
Do you really want to continue? (y/n): y
[site http://default] [TRIPAL ERROR] [GENOTYPES_LOADER] Incompatible postgresql version detected. You are using 9.2 and this module requires at least 9.3.
[site http://default] [TRIPAL ERROR] [GENOTYPES_LOADER] Incompatible postgresql version detected. You are using 9.2 and this module requires at least 9.3.
genotypes_loader was enabled successfully.                                                                                                                                                                                 [ok]
This module requires PostgreSQL 9.3 or higher.                                                                                                                                                                             [error]
This module requires PostgreSQL 9.3 or higher.                                                                                                                                                                             [error]
Your postgresql version is: 9.2                                                                                                                                                                                            [status]
__________________________________________________________________________
```

Unfortuantely no its still reporting my version as 9.2

**Comment by bradfordcondon** [comment]
If it helps, here is my version string that is failing hte regexp:

`PostgreSQL 10.5 on x86_64-apple-darwin, compiled by i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00), 64-bit"`

I like https://regex101.com/ or similar for testing regexp:

![Screen Shot 2019-04-06 at 7 11 24 PM](https://user-images.githubusercontent.com/7063154/55676275-d5b58c00-589f-11e9-8941-a9da9eb7df1b.png)


looks like your regexp is requiring my version to be of form 10.5.x . but its only 10.5 . I'm just goign to submit a PR that checks if the major version is > 9 and if so, is happy, if thats OK...


```php
    preg_match('/PostgreSQL (\d+)/', $version_string, $majors);

  if ((int) $majors[0] > 9) {
    $version = $majors[0];
    variable_set('pgsql_version', $version);
    return $version;
  }
```

seems to me that this works, just check the major version prior to checking the subversion.

**Comment by laceysanderson** [comment]
Opps, missed the difference between the format! I still think we should keep the subversion since we need to ensure it's greater then 9.2. If we just change the regex to not expect the sub-sub-version, (i.e.  `PostgreSQL (\d+\.\d+)`) it seems to work on both our version strings.

<img width="1225" alt="Screen Shot 2019-04-08 at 9 30 48 AM" src="https://user-images.githubusercontent.com/1566301/55736676-05b87880-59e1-11e9-9431-17c13865652c.png">

**Comment by bradfordcondon** [comment]
either way is fine with me, my proposed way you only check the subversion if the primary version is 9.  You need to do that either way, since you dont want 10.2 to fail, just 9.2

edit- oops i meant to make a PR and forgot, sorry.  ill get to it today hopefully

**Comment by bradfordcondon** [comment]
This issue still causes errors on postgres 10+

**Comment by laceysanderson** [comment]
Ah yes, I see a couple problems still existing here. @carolyncaron look at https://github.com/UofS-Pulse-Binfo/nd_genotypes/blob/7.x-3.x/api/nd_genotypes.api.inc#L110-L139

Specifically, note 

[`preg_match('/PostgreSQL (\d+\.\d+)/', $version_string, $matches)`](https://github.com/UofS-Pulse-Binfo/nd_genotypes/blob/7.x-3.x/api/nd_genotypes.api.inc#L121)

which doesn't try to capture a third digit and 

[`return variable_get('pgsql_version', nd_genotypes_recheck_postgresql_version());`](https://github.com/UofS-Pulse-Binfo/nd_genotypes/blob/7.x-3.x/api/nd_genotypes.api.inc#L138)

which ensures the version is actually checked if the variable is not set.

**Comment by laceysanderson** [comment]
It should be fixed via the latest merged PR. I tested it locally on PostgreSQL 11.3 and it worked 😬
