### ISSUE TITLE
Marker Type

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/vcf_genotypes#3]
Currently you describe the "Marker Type" under --help as 'The Sequence Ontology (SO) term name that describes the marker technology used to generate the genotypes in the file (e.g. "Exome Capture", "GBS", "KASPar", etc.).'

However, this is the featureprop.value marker type and as such is a free-text descriptor not an SO term. I also noticed in https://github.com/UofS-Pulse-Binfo/genotypes_loader/blob/master/includes/genotypes_loader.genotype_matrix.inc#L17 that you defined marker type wrong there too though it looks like you used it correctly.

Please clean-up documentation to ensure that you are clear which marker type it is. The mix-up in help caused me to supply the wrong value when loading :-(

**Comment by carolyncaron** [comment]
Documentation has been updated - please review!

**Comment by laceysanderson** [comment]
Awesome :-) Thanks!
