### ISSUE TITLE
why arent required cv terms inserted on install?

### ISSUE THREAD

**Issue by bradfordcondon** [UofS-Pulse-Binfo/vcf_genotypes#34]
Basically #8 (for example, `is_marker_of`).  Has your thinking on this changed over time?  I think you'll find inserting the terms expected by this module is necessary for the Tripal badge ie #30 .  You could keep the customization form, but inserting the default terms on install would be nice (and IMO necessary badge requirement).

worst case, how about just including a PHP script that inserts the expected terms?

**Comment by laceysanderson** [comment]
PR Merged. Thank you for bringing this to our attention!
