### ISSUE TITLE
readme says is_marker_of is from stock_relationship but its feature_relationship

### ISSUE THREAD

**Issue by bradfordcondon** [UofS-Pulse-Binfo/vcf_genotypes#36]
I get this error

`ERROR: Could not find type 'is_marker_of' with vocabulary 'feature_relationship'.                      [error]`

despite running this term insert:

```php

    chado_insert_cvterm([
      'id' => 'local:is_marker_of',
      'name' => 'is_marker_of',
      'cv_name' => 'stock_relationship',
      'definition' => 'Local term from the genotypes_loader module.'
    ]);
```

looks like the README says it needs it in the wrong CV.

**Comment by laceysanderson** [comment]
Thanks for pointing this out! It's now fixed in the README
