### ISSUE TITLE
Link markers to the project using the chado project_feature table

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/vcf_genotypes#46]
Currently the module stores genotypic calls including the project from which those calls are generated from. However, we are missing the link between markers and project which makes searching for markers by project name difficult. Therefore, the module needs to add an insert into the project_feature table in chado for each marker that is inserted. 

Note: This update needs to occur for each of the file types that can be loaded.

**Comment by laceysanderson** [comment]
Fixed!
