### ISSUE TITLE
Chromosome error

### ISSUE THREAD

**Issue by Xaiku** [UofS-Pulse-Binfo/vcf_genotypes#50]
- Tripal Version: v3
- Drupal Version: 7.69
- PostgreSQL Version: PostgreSQL 13.0 (Ubuntu 13.0-1.pgdg18.04+1)
- PHP Version: 7.3.23-1+ubuntu18.04.1+deb.sury.org+1)

Hey everybody,

I am trying to load in the sample files that comes with genotype loader, but I get the following error:
![image](https://user-images.githubusercontent.com/73877812/99072751-eb7b4f00-25b4-11eb-9dc3-96b450970c8d.png)

This is my Tripal content type:
![image](https://user-images.githubusercontent.com/73877812/99072936-44e37e00-25b5-11eb-8947-544879fae974.png)

This is my chromosome Tripal content:
![image](https://user-images.githubusercontent.com/73877812/99072862-1d8cb100-25b5-11eb-9708-babc86295cc8.png)

**Comment by carolyncaron** [comment]
Hi Xaiku, thank you for reaching out! Unfortunately I'm having issues replicating the error you're seeing. The error shows for me before I create the chromosome content type and content, but then creating them resolves it and the data is loaded in. From what I can tell in your screenshots, you've set up things correctly. Can you show me the exact load-genotypes command you used? 

Also, to verify the chromosome is in your database, can you try the following SQL query using drush:
`drush sql-query "SELECT o.genus, o.species, cvt.name as type_name, cv.name as type_cv, dbx.accession as type_accession, f.name, f.uniquename 
FROM chado.feature f 
LEFT JOIN chado.organism o ON o.organism_id=f.organism_id 
LEFT JOIN chado.cvterm cvt ON cvt.cvterm_id=f.type_id 
LEFT JOIN chado.cv ON cv.cv_id=cvt.cv_id 
LEFT JOIN chado.dbxref dbx ON dbx.dbxref_id=cvt.dbxref_id 
WHERE f.name='LcChr1';"`

You would expect to see output like:
`Tripalus databasica chromosome sequence 0000340 LcChr1 LcChr1`

**Comment by Xaiku** [comment]
Hey @carolyncaron,

I tried the SQL query using drush and my output was empty. The load-genotypes command I used is from the old README.md. This is the command: drush load-genotypes sample_files/sample.vcf sample_files/samples.list --organism="Tripalus databasica" --variant-type="SNP" --marker-type="genetic_marker" --project-name="My SNP Discovery Project" --ndgeolocation="here".

**Comment by carolyncaron** [comment]
Ok, the empty output from your query definitely explains why the loader is unable to find your chromosome! As for why it is isn't showing up where expected, one cause might be as simple as an extra whitespace at the end of your chromosome identifier. You can check for that when trying to edit your Tripal content page. If that doesn't appear to be the issue, then can you try the following query to see what chromosomes are stored for your organism?

`drush sql-query "SELECT '(' || o.genus || ')', '(' || o.species || ')', '(' || cvt.name || ')' as type_name, '(' || cv.name || ')' as type_cv, '(' || dbx.accession || ')' as type_accession, '(' || f.name || ')', '(' || f.uniquename || ')' FROM chado.feature f LEFT JOIN chado.organism o ON o.organism_id=f.organism_id LEFT JOIN chado.cvterm cvt ON cvt.cvterm_id=f.type_id LEFT JOIN chado.cv ON cv.cv_id=cvt.cv_id LEFT JOIN chado.dbxref dbx ON dbx.dbxref_id=cvt.dbxref_id WHERE dbx.accession='0000340' AND o.species='databasica';"`

**Comment by Xaiku** [comment]
I checked if there was a whitespace at the end of the identifier, and there was no whitespace. I also tried the query and this is what I got:
![image](https://user-images.githubusercontent.com/73877812/99957501-18cfb600-2d88-11eb-93bb-27fc7d451ef9.png)

I also tried giving the tripal content a name and this is what I got:
Capital letter C
![image](https://user-images.githubusercontent.com/73877812/99957654-57fe0700-2d88-11eb-8d35-a59f9e4a33c9.png)
![image](https://user-images.githubusercontent.com/73877812/99957698-677d5000-2d88-11eb-8715-5ebcc33e3510.png)

Lowercase C
![image](https://user-images.githubusercontent.com/73877812/99957917-ba570780-2d88-11eb-8eb6-24af9034fa71.png)
![image](https://user-images.githubusercontent.com/73877812/99957949-c773f680-2d88-11eb-9702-bba5cb1208d8.png)

I still get the same error after changing the name, so that doesn't help

**Comment by carolyncaron** [comment]
I think I see the problem now! The fields for Name and Identifier of your chromosome both have to be filled out and they must also be identical (and match the the value in the #CHROM column in your VCF file). So if you change the Name to be "LcChr1" that should help. It's possible that this requirement might be too stringent, considering Chado is willing to store only the Identifier. I'll create an issue to look into it further, but for now, know that they do have to match!

**Comment by Xaiku** [comment]
I changed the name and it worked! Thank you very much!
![image](https://user-images.githubusercontent.com/73877812/100215049-df768200-2f10-11eb-89d8-f2b96f722242.png)
