### ISSUE TITLE
loading sample.vcf and samples.list

### ISSUE THREAD

**Issue by cornellyujy** [UofS-Pulse-Binfo/vcf_genotypes#54]
Hello,
Following the instruction in the link (https://genotypes-loader.readthedocs.io/en/latest/demo.html) and using this command 'sudo drush load-genotypes sample.vcf samples.list --organism="Citrus sinensis" --variant-type="SNP" --marker-type="genetic_marker" --project-name="Citrus Demonstration Genotypic Data"', I got this error:
################
Begin validating options and samples...
  Loading your data according to the "Genotype Call Custom Table" Method.
  Found organism "Citrullus sinensis" in the database.
  Found project "Citrus Demonstration Genotypic Data" in the database.
  Checking for samples [Insert And Select] and for germplasm [Insert And Select] in the database...
ERROR: Could not find germplasm type 'accession' with the vocabulary 'GCP germplasm ontology'.
################
I am not sure if it means I should install the GCP germplasm ontology. Thanks~

**Comment by carolyncaron** [comment]
Hi! Thank you for bringing this to my attention.

It looks like I made an assumption about the vocabulary based on the database I work with, but by default Tripal uses the "germplasm_ontology" vocabulary. I'll get this fixed to work for all Tripal databases as soon as I can, but in the meantime, here is a patch you can use to get rid of the error: [germplasm_ontology_fix.patch.txt](https://github.com/UofS-Pulse-Binfo/genotypes_loader/files/8028113/germplasm_ontology_fix.patch.txt)

You can apply this patch by using `git apply germplasm_ontology_fix.patch.txt` within the genotypes_loader directory. Please let me know if you still run into issues with this. Thanks!

**Comment by cornellyujy** [comment]
Hello @carolyncaron , many thanks for your help. Follow your steps, I downloaded this patch using wget, and run the command git. I got this error:
##########################################
$ sudo git apply germplasm_ontology_fix.patch.txt
error: patch failed: genotypes_loader.drush.inc:327
error: genotypes_loader.drush.inc: patch does not apply
##########################################
Is it wrong for running this patch? Thanks!

**Comment by cornellyujy** [comment]
Hello, I chmod its permission, and it works. Thanks!

**Comment by cornellyujy** [comment]
Hello @carolyncaron , I found the sample files were wrong. I am not sure if you can supply right set of data. So I can use your data to make it run. Thanks~

**Comment by carolyncaron** [comment]
Hi @cornellyujy, I'm sorry you ran into issues again. I was able to load successfully using the sample.vcf and samples.list files. Can you provide any additional information? Are there any errors that appear on the console?

**Comment by cornellyujy** [comment]
Hi @carolyncaron , I knew the reason why I got the errors. I fellow the steps from stephen's tripal to build the Organism. In the chado.feature, the chromosome name: scaffold00001 was existed after loading feature data into chado.feature. But your sample data supplied another chromosome name. So I will update the data to make it run.

**Comment by cornellyujy** [comment]
Hello, I just want to know how did you transfer vcf format to Genotype Matrix and Genotype Flat-file? Thanks~

**Comment by cornellyujy** [comment]
Hi @carolyncaron , I loaded the sample
