### ISSUE TITLE
Best Practice for Inserting Required Terms 

### ISSUE THREAD

**Issue by ehsueh** [UofS-Pulse-Binfo/vcf_genotypes#8]
Hi,
Firstly, thank you for developing and maintaining this module! 
I am trying to load a vcf file using `drush load-genotypes` however, I am getting the error 

> ERROR: Could not find type 'DNA' with vocabulary 'stock_type'

It seems that I do not have the required term 'DNA' for in my controlled vocabulary table. May I ask what is the best practice for adding vocabularies and terms? Or do people usually just log in to their postgres db and insert terms as they come up?
Thank you :smile:

**Comment by laceysanderson** [comment]
Hi @ehsueh 

Best practice in Tripal for adding vocabularies and terms is to load a public ontology through the Tripal Ontology loader. For example, the sequence ontology contains a number of terms used by this loader and should be loaded into your Tripal site. This is included in the tripal tutorial here: http://tripal.info/tutorials/v2.x/installation/tripal#toc-controlled-vocabularies-installing-cvs--8sSsaDNy

Now, those best practices are all well and good as long as there is a public ontology for the data you are loading. In the case of this loader, there are not good public ontologies for germplasm, stocks and relationships *cue sad face*. To get around this we have added a configuration screen to the most recent development version of this module to allow you to choose existing terms and/or create terms as needed. You can access this configuration form through the Drupal administration menu > Tripal > Extensions > Genotypes Loader ( [your site]/admin/tripal/extension/genotypes_loader ).
![screen shot 2017-04-25 at 4 12 17 pm](https://cloud.githubusercontent.com/assets/1566301/25410164/69e919fe-29d2-11e7-8f50-31457c293024.png)
The helpful checkmark tells if you the terms exist for your site. If you wanted to change the terms to something else (for example if you did find a public ontology to use *Yay!*) then you can just enter the term name in the text box and it will re-check. If you want to add any terms you were unable to find, simply check the "Add Terms if they don't exist?" checkbox and click "Save Terms" and they will be added :-)

**Comment by ehsueh** [comment]
Hi @laceysanderson,

Thank you very much! :smile:  Your detailed answer was very helpful.

What if the term is for a vocabulary that is not in the extension's template? For example, in the 6th column of my sample list, I have the term "Individual" for Germplasm_type. However, I don't have this type in my vocabulary and the template doesn't have a field for "Feature Property: germplasm_type". Can I use the "Feature Property: marker_type" textbox? I don't want it to be misused as the type_id for marker_type though. 

Thanks again.

**Comment by laceysanderson** [comment]
Ah yes, I had forgotten about the flexible germplasm type column in the sample file. You were right to be leery of using the "Feature Property: marker_type" textbox as the loader would then incorrectly use that term as the marker type.

Instead, Tripal provides an interface for managing controlled vocabularies and terms. You can access this interface form through the Drupal administration menu > Tripal > Chado Modules > Controlled Vocabularies. Then click the terms tab at the top right of the screen. This brings you to a search where you can see all the terms available in a given ontology. 

The germplasm types should be stored in the "stock_type" ontology. You can add a term to this vocabulary by clicking the "Add Term" link at the top of the Vocabulary terms search. Make sure to select "stock_type" from the "Controlled Vocabulary (Ontology) Name" drop-down. Also, keep in mind that these terms are case sensitive.

**Comment by ehsueh** [comment]
Thank you very much for your help @laceysanderson! It's loading now!
I was still getting the error about missing germplasm_type after adding the term with "stock_type" selected. I added the same term "Individual" with "feature_property" selected in the "Controlled Vocabulary (Ontology) Name" drop-down menu too. It seemed to have fixed it. Thanks again!
